[project]
name = "arena-3-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "accelerate>=1.13.0",
    "anthropic>=0.86.0",
    "bitsandbytes>=0.49.2",
    "circuitsvis",
    "diffusers>=0.37.0",
    "docformatter>=1.7.7",
    "eindex-callum>=0.1.2",
    "einops>=0.8.2",
    "frozendict>=2.4.7",
    "ftfy>=6.3.1",
    "gdown>=5.2.1",
    "gymnasium[accept-rom-license,atari,mujoco-py,other]==0.29.0",
    "hdbscan>=0.8.41",
    "huggingface-hub>=1.7.2",
    "imageio-ffmpeg>=0.6.0",
    "inspect-ai>=0.3.69",
    "instructor>=1.14.5",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jaxtyping>=0.3.9",
    "jupyter>=1.1.1",
    "jupyterlab-widgets>=3.0.16",
    "matplotlib>=3.10.8",
    "mediapy>=1.2.6",
    "mujoco>=3.6.0",
    "nbformat>=5.10.4",
    "neel-plotly",
    "nnsight>=0.6.3",
    "notebook>=7.5.5",
    "numpy-stl>=3.2.0",
    "openai>=2.29.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "peft>=0.18.1",
    "plotly>=6.6.0",
    "portalocker>=3.2.0",
    "pre-commit>=4.5.1",
    "pygame>=2.6.1",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "sae-lens>=6.39.0",
    "sae-vis>=0.2.15",
    "safetensors>=0.7.0",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.3.0",
    "streamlit>=1.55.0",
    "streamlit-antd-components>=0.3.2",
    "streamlit-image-select>=0.6.0",
    "streamlit-on-hover-tabs>=1.0.1",
    "tabulate>=0.10.0",
    "tiktoken>=0.12.0",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchinfo>=1.8.0",
    "torchtext>=0.18.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
    "transformer-lens>=2.16.1",
    "typeguard>=4.5.1",
    "umap-learn>=0.5.11",
    "wandb>=0.25.1",
    "wikipedia>=1.4.0",
]

[tool.ruff]
line-length = 100

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"

[tool.uv.sources]
circuitsvis = { git = "https://github.com/callummcdougall/CircuitsVis.git", subdirectory = "python" }
neel-plotly = { git = "https://github.com/neelnanda-io/neel-plotly" }

[tool.ruff.lint]
ignore = ["E722", "E731", "F722", "E402", "E741"]
extend-select = ["I"]
